name: "Flask Add-on"
version: "1.0.0"
slug: "flask_addon"
description: "Executa um servidor Flask dentro do Home Assistant."
startup: application
boot: auto
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
  - i386
options: {}
schema: {}
ports:
  5000/tcp: 5000